name: .NET Core

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore "BookLandApi/BookLandApi.sln"
    - name: Build
      run: dotnet build "BookLandApi/BookLandApi.sln" --configuration Release --no-restore
    - name: Test
      run: dotnet test "BookLandApi/BookLandApi.sln" --no-restore --verbosity normal
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.4

